const icons={home:'<path d="M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3z"/>',folder:'<path d="M3 6h7l2 2h9v11H3z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/>',note:'<path d="M5 3h14v18H5zM8 8h8m-8 4h8m-8 4h5"/>',plus:'<path d="M12 5v14M5 12h14"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',upload:'<path d="M12 16V4m-5 5 5-5 5 5M5 15v5h14v-5"/>',chevron:'<path d="m9 18 6-6-6-6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',grid:'<rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><rect x="14" y="14" width="6" height="6"/>',list:'<path d="M8 6h12M8 12h12M8 18h12M4 6h.01M4 12h.01M4 18h.01"/>',file:'<path d="M6 2h8l5 5v15H6zM14 2v6h5"/>',arrow:'<path d="m9 18 6-6-6-6"/>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24">${icons[el.dataset.icon]}</svg>`);
const defaults={
 folders:[{title:'Work projects',detail:'8 documents · 2 folders · 24.6 MB'},{title:'Personal',detail:'12 documents · 3 folders · 41.2 MB'},{title:'Finance',detail:'6 documents · 1 folder · 8.7 MB'},{title:'Resources',detail:'18 documents · 4 folders · 92.4 MB'}],
 notes:[{title:'Q4 planning ideas',text:'Focus areas for the next team planning session.',date:'Today'},{title:'Client meeting',text:'Follow up on the revised proposal and timeline.',date:'Yesterday'},{title:'Books to read',text:'The Creative Act, Slow Productivity, and Build.',date:'Sep 28'},{title:'Project Atlas',text:'Draft launch checklist and assign owners.',date:'Sep 25'}],
 reminders:[{title:'Team check-in',type:'Work',date:'Today, 10:30 AM'},{title:'Renew passport',type:'Personal',date:'Oct 5, 9:00 AM'},{title:'Thanksgiving break',type:'Holiday',date:'Oct 12, All day'}],
 files:[{title:'Project proposal.pdf',meta:'PDF · 2.4 MB'},{title:'Budget tracker.xlsx',meta:'Excel · 886 KB'},{title:'Meeting notes.docx',meta:'Word · 124 KB'}]
};
const saved=JSON.parse(localStorage.getItem('saile-data')||'null'); const data=saved||defaults; let page='home',grid=false,formType='note';
const main=document.getElementById('main'); const persist=()=>localStorage.setItem('saile-data',JSON.stringify(data));
function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page)); ({home:renderHome,sections:renderSections,reminders:renderReminders,notes:renderNotes}[page])(); hydrateIcons()}
function hydrateIcons(){document.querySelectorAll('[data-icon]:empty').forEach(el=>el.innerHTML=`<svg viewBox="0 0 24 24">${icons[el.dataset.icon]}</svg>`)}
function renderHome(){main.innerHTML=`<p class="eyebrow">Friday, October 2</p><h1 class="page-title">Good morning, Alex</h1><section class="hero"><p>Your workspace</p><h2>Everything you need, right where you left it.</h2></section><div class="stats"><div class="stat-card"><span class="stat-icon" data-icon="note"></span><strong>${data.notes.length}</strong><span>Total notes</span></div><div class="stat-card"><span class="stat-icon" data-icon="file"></span><strong>${data.files.length}</strong><span>Documents</span></div><div class="stat-card wide"><span class="stat-icon" data-icon="calendar"></span><div><strong>${data.reminders.length} upcoming</strong><span>${data.reminders[0]?.title||'Nothing scheduled'}</span></div><span class="arrow" data-icon="arrow"></span></div></div><div class="section-head"><h2>Recent files</h2><button class="text-btn" onclick="go('sections')">See all</button></div><div class="recent-list">${data.files.slice(0,3).map(file=>`<div class="file-row"><span class="file-icon" data-icon="file"></span><div><b>${esc(file.title)}</b><small>${esc(file.meta)}</small></div><i data-icon="chevron"></i></div>`).join('')}</div>`}
function renderSections(){main.innerHTML=`<p class="eyebrow">Your workspace</p><h1 class="page-title">Sections</h1><div class="search"><i data-icon="search"></i><input placeholder="Search folders and files"></div><div class="controls"><span style="font-size:13px;color:var(--muted)">${data.folders.length} folders</span><div class="segmented"><button class="${!grid?'active':''}" onclick="setGrid(false)" data-icon="list" aria-label="List"></button><button class="${grid?'active':''}" onclick="setGrid(true)" data-icon="grid" aria-label="Grid"></button></div></div><div class="folder-list ${grid?'grid':''}">${data.folders.map(f=>`<div class="folder-card"><span class="folder-icon" data-icon="folder"></span><div><b>${esc(f.title)}</b><small>${esc(f.detail)}</small></div><i class="arrow" data-icon="chevron"></i></div>`).join('')}</div>`}
function renderReminders(){const days=[['MON','28'],['TUE','29'],['WED','30'],['THU','1'],['FRI','2']];main.innerHTML=`<p class="eyebrow">Stay on schedule</p><h1 class="page-title">Reminders</h1><div class="calendar-strip">${days.map((d,i)=>`<button class="day ${i===4?'active':''}">${d[0]}<b>${d[1]}</b></button>`).join('')}</div><div class="section-head"><h2>Upcoming</h2><button class="text-btn">Calendar</button></div><div class="reminder-list">${data.reminders.map(r=>`<div class="reminder-card"><span class="reminder-dot ${r.type.toLowerCase()}"></span><div><b>${esc(r.title)}</b><small>${esc(r.date)}</small></div><span class="tag">${esc(r.type)}</span></div>`).join('')}</div>`}
function renderNotes(){main.innerHTML=`<p class="eyebrow">Capture your thoughts</p><h1 class="page-title">Notes</h1><div class="search"><i data-icon="search"></i><input placeholder="Search notes"></div><div class="note-list">${data.notes.map(n=>`<article class="note-card"><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><small>${esc(n.date)}</small></article>`).join('')}</div>`}
window.go=p=>{page=p;render()}; window.setGrid=x=>{grid=x;render()};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));
const sheet=document.getElementById('actionSheet'),back=document.getElementById('sheetBackdrop'); const toggleSheet=x=>{sheet.classList.toggle('open',x);back.classList.toggle('open',x)}; document.getElementById('createBtn').onclick=()=>toggleSheet(true); document.getElementById('closeSheet').onclick=()=>toggleSheet(false);back.onclick=()=>toggleSheet(false);
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{toggleSheet(false);const a=b.dataset.action;if(a==='upload'){document.getElementById('fileInput').click();return}openForm(a)});
const modal=document.getElementById('modalBackdrop');function openForm(type){formType=type;document.getElementById('formTitle').textContent={note:'Create note',reminder:'Add reminder',folder:'New folder'}[type];document.getElementById('detailsLabel').classList.toggle('hidden',type==='folder');document.getElementById('typeLabel').classList.toggle('hidden',type!=='reminder');document.getElementById('dateLabel').classList.toggle('hidden',type!=='reminder');modal.classList.add('open')}document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
document.getElementById('itemForm').onsubmit=e=>{e.preventDefault();const title=document.getElementById('titleInput').value,detail=document.getElementById('detailsInput').value;if(formType==='note')data.notes.unshift({title,text:detail||'New note',date:'Just now'});if(formType==='folder')data.folders.unshift({title,detail:'0 documents · 0 folders · 0 KB'});if(formType==='reminder')data.reminders.unshift({title,type:document.getElementById('typeInput').value,date:document.getElementById('dateInput').value||'No date'});persist();e.target.reset();modal.classList.remove('open');showToast('Saved to Saile');render()};
document.getElementById('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;data.files.unshift({title:f.name,meta:`${f.name.split('.').pop().toUpperCase()} · ${Math.max(1,Math.round(f.size/1024))} KB`});persist();showToast('Document uploaded');render()};function showToast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}render();
