data.profile=data.profile||{};data.files.forEach(f=>f.data=f.data||'');data.notes.forEach(n=>n.locked=!!n.locked);save();
const baseRender=render;render=function(){baseRender();decorate()};
function decorate(){document.querySelectorAll('.note-card').forEach(card=>{const i=+card.closest('.swipe-wrap').dataset.i,n=data.notes[i];card.dataset.group=n.group;if(n.locked){card.classList.add('locked');card.querySelector('p').textContent='Locked note';card.insertAdjacentHTML('afterbegin',`<span class="lock-badge">${svg('lock')} Locked</span>`)}});if(data.profile.avatar){profileBtn.innerHTML=`<img src="${data.profile.avatar}" alt="Profile">`}document.querySelectorAll('[data-icon]:empty').forEach(e=>e.innerHTML=svg(e.dataset.icon))}decorate();

fileInput.onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{data.files.unshift({title:f.name,meta:`${f.name.split('.').pop().toUpperCase()}, ${Math.max(1,Math.round(f.size/1024))} KB`,folderId:currentFolder,data:reader.result,mime:f.type});save();page='sections';render();toast(currentFolder?'Uploaded to this section':'Document uploaded');e.target.value=''};reader.onerror=()=>toast('Could not read this file');reader.readAsDataURL(f)};

function findFile(row){const name=row.querySelector('b')?.textContent;return data.files.find(f=>f.title===name)}
main.addEventListener('click',e=>{const folder=e.target.closest('[data-pick]');if(folder&&!selecting){currentFolder=data.folders[+folder.dataset.pick].id;render();return}const row=e.target.closest('.file-row');if(row){const f=findFile(row);if(f)openDocument(f)}},{capture:true});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="upload"]')&&page!=='sections')currentFolder=null;if(e.target.closest('.nav-item[data-page="sections"]')&&page!=='sections')currentFolder=null},{capture:true});

let viewingFile=null;function openDocument(f){viewingFile=f;viewerTitle.textContent=f.title;viewerMeta.textContent=f.meta;viewerBody.innerHTML='';const ext=f.title.split('.').pop().toLowerCase();if(!f.data){viewerBody.innerHTML='<div class="viewer-empty">This older upload has no stored preview. Upload it again to view it here.</div>'}else if(ext==='pdf'){viewerBody.innerHTML=`<iframe src="${f.data}" title="${esc(f.title)}"></iframe>`}else if(ext==='txt'){fetch(f.data).then(r=>r.text()).then(t=>viewerBody.innerHTML=`<pre>${esc(t)}</pre>`)}else{viewerBody.innerHTML=`<div class="viewer-empty">${icon('file')}<b>${esc(f.title)}</b><p>Preview is not available for this format.</p></div>`}externalOpen.disabled=!f.data;viewerBackdrop.classList.add('open')}
viewerClose.onclick=()=>viewerBackdrop.classList.remove('open');viewerBackdrop.onclick=e=>{if(e.target===viewerBackdrop)viewerBackdrop.classList.remove('open')};externalOpen.onclick=()=>{if(!viewingFile?.data)return;const a=document.createElement('a');a.href=viewingFile.data;a.download=viewingFile.title;a.target='_blank';a.click()};

profileBtn.onclick=()=>profileMenu.classList.toggle('open');document.addEventListener('click',e=>{if(!e.target.closest('#profileMenu')&&!e.target.closest('#profileBtn'))profileMenu.classList.remove('open')});
profileMenu.onclick=e=>{const action=e.target.dataset.profile;if(!action)return;profileMenu.classList.remove('open');if(action==='avatar')avatarInput.click();if(action==='password')changePassword();if(action==='backup')backupBackdrop.classList.add('open');if(action==='logout'){toast('Logged out');page='home';render()}};
avatarInput.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{data.profile.avatar=r.result;save();decorate();toast('Avatar updated')};r.readAsDataURL(f)};
function changePassword(){const current=data.profile.password;if(current&&prompt('Current password')!==current){toast('Current password is incorrect');return}const next=prompt('New password');if(!next)return;const confirm=prompt('Confirm new password');if(next!==confirm){toast('Passwords do not match');return}data.profile.password=next;save();toast('Password changed')}

backupClose.onclick=()=>backupBackdrop.classList.remove('open');backupBackdrop.onclick=e=>{if(e.target===backupBackdrop)backupBackdrop.classList.remove('open')};restoreBtn.onclick=()=>restoreInput.click();document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportData(b.dataset.export));
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportData(format){if(format==='json')download('saile-backup.json','application/json',JSON.stringify(data,null,2));else{const rows=['collection,data'];['folders','notes','reminders','files','noteGroups','profile'].forEach(k=>rows.push(`${k},${btoa(unescape(encodeURIComponent(JSON.stringify(data[k]))))}`));download('saile-backup.csv','text/csv',rows.join('\n'))}toast('Backup exported')}
restoreInput.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{let restored;if(f.name.toLowerCase().endsWith('.json'))restored=JSON.parse(r.result);else{restored={};r.result.split(/\r?\n/).slice(1).filter(Boolean).forEach(line=>{const p=line.indexOf(',');restored[line.slice(0,p)]=JSON.parse(decodeURIComponent(escape(atob(line.slice(p+1)))))})}if(!restored.notes||!restored.folders)throw Error();Object.keys(data).forEach(k=>delete data[k]);Object.assign(data,restored);save();backupBackdrop.classList.remove('open');page='home';render();toast('Backup restored')}catch{toast('This backup could not be restored')}};r.readAsText(f);e.target.value=''};

let drag=null;main.addEventListener('pointerdown',e=>{const wrap=e.target.closest('.note-list .swipe-wrap');if(!wrap)return;e.stopImmediatePropagation();const i=+wrap.dataset.i;drag={wrap,i,x:e.clientX,y:e.clientY,held:false,moved:false,timer:setTimeout(()=>{if(drag){drag.held=true;wrap.classList.add('dragging');navigator.vibrate?.(25)}},450)}},{capture:true});
main.addEventListener('pointermove',e=>{if(!drag)return;e.stopImmediatePropagation();const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>8||Math.abs(dy)>8)drag.moved=true;if(!drag.held){if(Math.abs(dx)>12||Math.abs(dy)>12)clearTimeout(drag.timer);return}drag.wrap.style.transform=`translate(${dx}px,${dy}px)`;document.querySelectorAll('.group-tabs button:not(.add-group)').forEach(b=>{const r=b.getBoundingClientRect();b.classList.toggle('drop-target',e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top-30&&e.clientY<=r.bottom+30)})},{capture:true});
main.addEventListener('pointerup',e=>{if(!drag)return;e.stopImmediatePropagation();clearTimeout(drag.timer);const dx=e.clientX-drag.x,n=data.notes[drag.i];if(drag.held){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.group-tabs button:not(.add-group)');if(target){n.group=target.textContent.trim();save();toast(`Moved to ${n.group}`);render()}else if(dx<-55){toggleNoteLock(n);render()}else resetDrag()}else if(dx<-70){data.notes.splice(drag.i,1);save();render();toast('Note deleted')}else if(!drag.moved){if(n.locked){const pass=prompt('Enter note password');toast(pass===n.password?'Note unlocked for viewing':'Incorrect password')} }else resetDrag();drag=null},{capture:true});
function resetDrag(){if(!drag)return;drag.wrap.style.transform='';drag.wrap.classList.remove('dragging');document.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'))}
function toggleNoteLock(n){if(n.locked){const pass=prompt('Enter this note password to remove the lock');if(pass!==n.password){toast('Incorrect password. Delete the note if the password is lost.');return}n.locked=false;delete n.password;save();toast('Note unlocked')}else{const pass=prompt('Set a password for this note');if(!pass)return;const confirm=prompt('Confirm note password');if(pass!==confirm){toast('Passwords do not match');return}n.locked=true;n.password=pass;save();toast('Note locked')}}
