const appRenderV1=render;render=function(){appRenderV1();prepareNotesV2()};
function prepareNotesV2(){if(page!=='notes')return;const search=main.querySelector('.search input');if(search){search.addEventListener('input',()=>filterNotes(search.value));search.placeholder='Search notes (3 characters minimum)'}main.querySelectorAll('.note-list .swipe-wrap').forEach(w=>{const i=+w.dataset.i,n=data.notes[i];w.insertAdjacentHTML('afterbegin',`<button class="note-lock-action" data-note-action="lock" data-i="${i}">${svg('lock')}<span>${n.locked?'Unlock':'Lock'}</span></button>`);w.querySelector('.swipe-delete').outerHTML=`<button class="swipe-delete" data-note-action="delete" data-i="${i}">${svg('trash')}<span>Delete</span></button>`;w.querySelector('.note-card').dataset.noteIndex=i})}
function filterNotes(q){const term=q.trim().toLowerCase();main.querySelectorAll('.note-list .swipe-wrap').forEach(w=>{const n=data.notes[+w.dataset.i];w.style.display=term.length<3||`${n.title} ${n.text} ${n.group}`.toLowerCase().includes(term)?'':'none'})}
let noteGesture=null;main.addEventListener('pointerdown',e=>{const content=e.target.closest('.note-list .swipe-content');if(!content)return;e.stopImmediatePropagation();const wrap=content.closest('.swipe-wrap');noteGesture={wrap,content,i:+wrap.dataset.i,x:e.clientX,y:e.clientY,held:false,timer:setTimeout(()=>{if(noteGesture){noteGesture.held=true;wrap.classList.add('dragging');navigator.vibrate?.(20)}},500)}},{capture:true});
main.addEventListener('pointermove',e=>{if(!noteGesture)return;e.stopImmediatePropagation();const dx=e.clientX-noteGesture.x,dy=e.clientY-noteGesture.y;if(noteGesture.held&&Math.abs(dy)>Math.abs(dx)){noteGesture.wrap.style.transform=`translate(${dx}px,${dy}px)`;document.querySelectorAll('.group-tabs button:not(.add-group)').forEach(b=>{const r=b.getBoundingClientRect();b.classList.toggle('drop-target',e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top-35&&e.clientY<=r.bottom+35)})}else{if(Math.abs(dx)>10)clearTimeout(noteGesture.timer);noteGesture.content.style.transform=`translateX(${Math.max(-92,Math.min(92,dx))}px)`}},{capture:true});
main.addEventListener('pointerup',e=>{if(!noteGesture)return;e.stopImmediatePropagation();clearTimeout(noteGesture.timer);const g=noteGesture,dx=e.clientX-g.x,dy=e.clientY-g.y;if(g.held&&Math.abs(dy)>Math.abs(dx)){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.group-tabs button:not(.add-group)');if(target){data.notes[g.i].group=target.textContent.trim();save();toast(`Moved to ${data.notes[g.i].group}`);render()}else resetGesture(g)}else if(dx<-45)g.content.style.transform='translateX(-92px)';else if(dx>45)g.content.style.transform='translateX(92px)';else{g.content.style.transform='';if(Math.abs(dx)<8&&Math.abs(dy)<8)showFullNote(g.i)}noteGesture=null},{capture:true});
function resetGesture(g){g.wrap.style.transform='';g.wrap.classList.remove('dragging');g.content.style.transform='';document.querySelectorAll('.drop-target').forEach(x=>x.classList.remove('drop-target'))}
main.addEventListener('click',e=>{const action=e.target.closest('[data-note-action]');if(!action)return;e.stopImmediatePropagation();const i=+action.dataset.i;if(action.dataset.noteAction==='delete'){data.notes.splice(i,1);save();render();toast('Note deleted')}else showLockModal(i)},{capture:true});
function ensureNoteModal(){if(document.getElementById('noteViewBackdrop'))return;document.body.insertAdjacentHTML('beforeend',`<div class="note-view-backdrop" id="noteViewBackdrop"><section class="note-view"><button class="note-view-close">${svg('close')}</button><span id="noteViewGroup"></span><h2 id="noteViewTitle"></h2><div id="noteViewText"></div><div id="noteViewExtras"></div></section></div>`);noteViewBackdrop.onclick=e=>{if(e.target===noteViewBackdrop||e.target.closest('.note-view-close'))noteViewBackdrop.classList.remove('open')}}
function showFullNote(i){const n=data.notes[i];if(n.locked&&prompt('Enter this note password')!==n.password){toast('Incorrect password');return}ensureNoteModal();noteViewGroup.textContent=n.group;noteViewTitle.textContent=n.title;noteViewText.textContent=n.text;noteViewExtras.innerHTML=`${n.summary?`<div><b>Photo summary</b><p>${esc(n.summary)}</p></div>`:''}${n.drawing?`<div><b>Drawing</b><img src="${n.drawing}" alt="Note drawing"></div>`:''}`;noteViewBackdrop.classList.add('open')}
function showLockModal(i){ensureLockModal();const n=data.notes[i];lockNoteIndex.value=i;lockModalTitle.textContent=n.locked?'Unlock note':'Lock note';lockCurrentWrap.classList.toggle('hidden',!n.locked);lockNewWrap.classList.toggle('hidden',n.locked);lockConfirmWrap.classList.toggle('hidden',n.locked);lockForm.reset();noteLockBackdrop.classList.add('open')}
function ensureLockModal(){if(document.getElementById('noteLockBackdrop'))return;document.body.insertAdjacentHTML('beforeend',`<div class="note-view-backdrop" id="noteLockBackdrop"><form class="password-modal" id="lockForm"><input type="hidden" id="lockNoteIndex"><button type="button" class="note-view-close">${svg('close')}</button><h2 id="lockModalTitle"></h2><label id="lockCurrentWrap">Note password<input id="lockCurrent" type="password"></label><label id="lockNewWrap">New password<input id="lockNew" type="password"></label><label id="lockConfirmWrap">Confirm password<input id="lockConfirm" type="password"></label><button class="primary-btn">Save</button><p>Lost note passwords cannot be reset. Delete the note instead.</p></form></div>`);noteLockBackdrop.onclick=e=>{if(e.target===noteLockBackdrop||e.target.closest('.note-view-close'))noteLockBackdrop.classList.remove('open')};lockForm.onsubmit=e=>{e.preventDefault();const n=data.notes[+lockNoteIndex.value];if(n.locked){if(lockCurrent.value!==n.password){toast('Incorrect password');return}n.locked=false;delete n.password;toast('Note unlocked')}else{if(!lockNew.value||lockNew.value!==lockConfirm.value){toast('Passwords do not match');return}n.locked=true;n.password=lockNew.value;toast('Note locked')}save();noteLockBackdrop.classList.remove('open');render()}}
prepareNotesV2();
