const tourSteps=[
  {title:'Welcome to Saile',text:'Keep sections, documents, notes, and reminders in one private workspace.',art:'<svg viewBox="0 0 260 160"><rect x="46" y="22" width="168" height="116" rx="8"/><path d="M72 51h54M72 72h116M72 93h82"/><circle cx="181" cy="111" r="20"/><path d="M181 101v20m-10-10h20"/></svg>'},
  {title:'Organize every file',text:'Create nested sections. Files uploaded inside a section stay there.',art:'<svg viewBox="0 0 260 160"><path d="M33 61h75l14 14h105v62H33z"/><path d="M62 39h61l12 12h67v24H33V61a22 22 0 0 1 29-22Z"/><path d="M75 101h110"/></svg>'},
  {title:'Notes that stay useful',text:'Group notes, draw, summarize photos, search, and protect individual notes.',art:'<svg viewBox="0 0 260 160"><rect x="51" y="25" width="104" height="116" rx="7"/><path d="M73 54h61M73 76h61M73 98h38"/><rect x="146" y="69" width="64" height="55" rx="7"/><path d="M162 86h32M162 102h22"/></svg>'},
  {title:'View and remember',text:'Read PDFs in Saile, open Office files externally, and schedule tagged reminders.',art:'<svg viewBox="0 0 260 160"><rect x="39" y="28" width="82" height="108" rx="7"/><path d="M58 52h44M58 72h44M58 92h29"/><rect x="137" y="45" width="87" height="78" rx="7"/><path d="M137 69h87M160 34v22m41-22v22"/><circle cx="181" cy="96" r="12"/></svg>'},
  {title:'Your data stays portable',text:'Export a JSON or CSV backup. Restore it from the profile menu.',art:'<svg viewBox="0 0 260 160"><path d="M66 28h91l37 37v67H66z"/><path d="M157 28v38h37M130 84v43m-18-17 18 17 18-17"/></svg>'}
];
let tourIndex=0;
document.body.insertAdjacentHTML('beforeend',`<div class="onboarding" id="onboarding"><section class="tour-card"><button class="tour-skip" id="tourSkip">Skip</button><div class="tour-art" id="tourArt"></div><div class="tour-copy"><span id="tourCount"></span><h1 id="tourTitle"></h1><p id="tourText"></p></div><div class="tour-footer"><div id="tourDots"></div><button id="tourNext">Next</button></div></section></div><div class="onboarding" id="profileSetup"><form class="setup-card" id="setupForm"><div class="setup-avatar" id="setupAvatar">${svg('camera')}</div><h1>Set up your profile</h1><p>Your name appears on the Home screen.</p><label>Name<input id="setupName" maxlength="40" required placeholder="Enter your name"></label><input id="setupImage" type="file" accept="image/*" hidden><button type="button" class="setup-photo" id="setupPhoto">Upload image</button><button class="setup-finish">Start using Saile</button></form></div>`);
function drawTour(){const s=tourSteps[tourIndex];tourArt.innerHTML=s.art;tourCount.textContent=`Tip ${tourIndex+1} of ${tourSteps.length}`;tourTitle.textContent=s.title;tourText.textContent=s.text;tourDots.innerHTML=tourSteps.map((_,i)=>`<i class="${i===tourIndex?'active':''}"></i>`).join('');tourNext.textContent=tourIndex===tourSteps.length-1?'Continue':'Next'}
function openSetup(){onboarding.classList.remove('open');profileSetup.classList.add('open');setupName.value=data.profile.name||''}
tourNext.onclick=()=>{if(tourIndex<tourSteps.length-1){tourIndex++;drawTour()}else openSetup()};tourSkip.onclick=openSetup;setupPhoto.onclick=()=>setupImage.click();setupImage.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{setupAvatar.innerHTML=`<img src="${r.result}" alt="Avatar preview">`;setupAvatar.dataset.image=r.result};r.readAsDataURL(f)};
setupForm.onsubmit=e=>{e.preventDefault();data.profile.name=setupName.value.trim();if(setupAvatar.dataset.image)data.profile.avatar=setupAvatar.dataset.image;save();localStorage.setItem('saile-onboarded','1');profileSetup.classList.remove('open');render();toast('Welcome to Saile')};
const onboardingRender=render;render=function(){onboardingRender();const title=main.querySelector('.page-title');if(page==='home'&&title)title.textContent=`Good morning, ${data.profile.name||'there'}`};render();drawTour();if(!localStorage.getItem('saile-onboarded'))onboarding.classList.add('open');
